export { default as Skeleton } from './Skeleton.vue'
export { default as SkeletonElement } from './SkeletonElement.vue'
export { default as SkeletonAvatar } from './SkeletonAvatar.vue'
export { default as SkeletonTitle } from './SkeletonTitle.vue'
export { default as SkeletonParagraph } from './SkeletonParagraph.vue'
export { default as SkeletonButton } from './SkeletonButton.vue'
export { default as SkeletonImage } from './SkeletonImage.vue'
export type { SkeletonProps } from './Skeleton.vue'
export type { SkeletonElementProps } from './SkeletonElement.vue'
export type { SkeletonAvatarProps } from './SkeletonAvatar.vue'
export type { SkeletonTitleProps } from './SkeletonTitle.vue'
export type { SkeletonParagraphProps } from './SkeletonParagraph.vue'
export type { SkeletonButtonProps } from './SkeletonButton.vue'
export type { SkeletonImageProps } from './SkeletonImage.vue'